/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Address model module.
 * @module BillaBear/model/Address
 * @version 1.0.0
 */
export default class Address {
  /**
   * Constructs a new <code>Address</code>.
   * @alias module:BillaBear/model/Address
   * @class
   * @param country {String} 
   */
  constructor(country) {
    this.country = country;
  }

  /**
   * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Address} obj Optional instance to populate.
   * @return {module:BillaBear/model/Address} The populated <code>Address</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Address();
      if (data.hasOwnProperty('company_name'))
        obj.companyName = ApiClient.convertToType(data['company_name'], 'String');
      if (data.hasOwnProperty('street_line_one'))
        obj.streetLineOne = ApiClient.convertToType(data['street_line_one'], 'String');
      if (data.hasOwnProperty('street_line_two'))
        obj.streetLineTwo = ApiClient.convertToType(data['street_line_two'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('postcode'))
        obj.postcode = ApiClient.convertToType(data['postcode'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} companyName
 */
Address.prototype.companyName = undefined;

/**
 * @member {String} streetLineOne
 */
Address.prototype.streetLineOne = undefined;

/**
 * @member {String} streetLineTwo
 */
Address.prototype.streetLineTwo = undefined;

/**
 * @member {String} city
 */
Address.prototype.city = undefined;

/**
 * @member {String} region
 */
Address.prototype.region = undefined;

/**
 * @member {String} country
 */
Address.prototype.country = undefined;

/**
 * @member {String} postcode
 */
Address.prototype.postcode = undefined;

