/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BillingAdmin model module.
 * @module BillaBear/model/BillingAdmin
 * @version 1.0.0
 */
export default class BillingAdmin {
  /**
   * Constructs a new <code>BillingAdmin</code>.
   * @alias module:BillaBear/model/BillingAdmin
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BillingAdmin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/BillingAdmin} obj Optional instance to populate.
   * @return {module:BillaBear/model/BillingAdmin} The populated <code>BillingAdmin</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BillingAdmin();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('display_name'))
        obj.displayName = ApiClient.convertToType(data['display_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
BillingAdmin.prototype.id = undefined;

/**
 * @member {String} displayName
 */
BillingAdmin.prototype.displayName = undefined;

