/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CheckoutSubscriptions model module.
 * @module BillaBear/model/CheckoutSubscriptions
 * @version 1.0.0
 */
export default class CheckoutSubscriptions {
  /**
   * Constructs a new <code>CheckoutSubscriptions</code>.
   * @alias module:BillaBear/model/CheckoutSubscriptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CheckoutSubscriptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/CheckoutSubscriptions} obj Optional instance to populate.
   * @return {module:BillaBear/model/CheckoutSubscriptions} The populated <code>CheckoutSubscriptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckoutSubscriptions();
      if (data.hasOwnProperty('plan'))
        obj.plan = ApiClient.convertToType(data['plan'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'String');
      if (data.hasOwnProperty('seat_number'))
        obj.seatNumber = ApiClient.convertToType(data['seat_number'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} plan
 */
CheckoutSubscriptions.prototype.plan = undefined;

/**
 * @member {String} price
 */
CheckoutSubscriptions.prototype.price = undefined;

/**
 * @member {Number} seatNumber
 */
CheckoutSubscriptions.prototype.seatNumber = undefined;

