/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CheckoutItems from './CheckoutItems';
import CheckoutSubscriptions from './CheckoutSubscriptions';

/**
 * The CheckoutBody model module.
 * @module BillaBear/model/CheckoutBody
 * @version 1.0.0
 */
export default class CheckoutBody {
  /**
   * Constructs a new <code>CheckoutBody</code>.
   * @alias module:BillaBear/model/CheckoutBody
   * @class
   * @param brand {String} 
   * @param customer {String} 
   */
  constructor(brand, customer) {
    this.brand = brand;
    this.customer = customer;
  }

  /**
   * Constructs a <code>CheckoutBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/CheckoutBody} obj Optional instance to populate.
   * @return {module:BillaBear/model/CheckoutBody} The populated <code>CheckoutBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckoutBody();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('brand'))
        obj.brand = ApiClient.convertToType(data['brand'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('customer'))
        obj.customer = ApiClient.convertToType(data['customer'], 'String');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [CheckoutItems]);
      if (data.hasOwnProperty('subscriptions'))
        obj.subscriptions = ApiClient.convertToType(data['subscriptions'], [CheckoutSubscriptions]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CheckoutBody.prototype.name = undefined;

/**
 * @member {String} brand
 */
CheckoutBody.prototype.brand = undefined;

/**
 * @member {String} slug
 */
CheckoutBody.prototype.slug = undefined;

/**
 * @member {String} customer
 */
CheckoutBody.prototype.customer = undefined;

/**
 * @member {Array.<module:BillaBear/model/CheckoutItems>} items
 */
CheckoutBody.prototype.items = undefined;

/**
 * @member {Array.<module:BillaBear/model/CheckoutSubscriptions>} subscriptions
 */
CheckoutBody.prototype.subscriptions = undefined;

