/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Cost model module.
 * @module BillaBear/model/Cost
 * @version 1.0.0
 */
export default class Cost {
  /**
   * Constructs a new <code>Cost</code>.
   * @alias module:BillaBear/model/Cost
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Cost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Cost} obj Optional instance to populate.
   * @return {module:BillaBear/model/Cost} The populated <code>Cost</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Cost();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
Cost.prototype.amount = undefined;

/**
 * @member {String} currency
 */
Cost.prototype.currency = undefined;

