/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CustomerIdUasgelimitBody model module.
 * @module BillaBear/model/CustomerIdUasgelimitBody
 * @version 1.0.0
 */
export default class CustomerIdUasgelimitBody {
  /**
   * Constructs a new <code>CustomerIdUasgelimitBody</code>.
   * @alias module:BillaBear/model/CustomerIdUasgelimitBody
   * @class
   * @param amount {Number} 
   * @param action {module:BillaBear/model/CustomerIdUasgelimitBody.ActionEnum} 
   */
  constructor(amount, action) {
    this.amount = amount;
    this.action = action;
  }

  /**
   * Constructs a <code>CustomerIdUasgelimitBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/CustomerIdUasgelimitBody} obj Optional instance to populate.
   * @return {module:BillaBear/model/CustomerIdUasgelimitBody} The populated <code>CustomerIdUasgelimitBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CustomerIdUasgelimitBody();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
CustomerIdUasgelimitBody.prototype.amount = undefined;

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
CustomerIdUasgelimitBody.ActionEnum = {
  /**
   * value: "WARNING"
   * @const
   */
  WARNING: "WARNING",

  /**
   * value: "DISABLE"
   * @const
   */
  DISABLE: "DISABLE"
};
/**
 * @member {module:BillaBear/model/CustomerIdUasgelimitBody.ActionEnum} action
 */
CustomerIdUasgelimitBody.prototype.action = undefined;

