/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Event model module.
 * @module BillaBear/model/Event
 * @version 1.0.0
 */
export default class Event {
  /**
   * Constructs a new <code>Event</code>.
   * @alias module:BillaBear/model/Event
   * @class
   * @param eventId {String} 
   * @param subscription {String} 
   * @param value {Number} 
   * @param code {String} 
   */
  constructor(eventId, subscription, value, code) {
    this.eventId = eventId;
    this.subscription = subscription;
    this.value = value;
    this.code = code;
  }

  /**
   * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Event} obj Optional instance to populate.
   * @return {module:BillaBear/model/Event} The populated <code>Event</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Event();
      if (data.hasOwnProperty('event_id'))
        obj.eventId = ApiClient.convertToType(data['event_id'], 'String');
      if (data.hasOwnProperty('subscription'))
        obj.subscription = ApiClient.convertToType(data['subscription'], 'String');
      if (data.hasOwnProperty('properties'))
        obj.properties = ApiClient.convertToType(data['properties'], Object);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} eventId
 */
Event.prototype.eventId = undefined;

/**
 * @member {String} subscription
 */
Event.prototype.subscription = undefined;

/**
 * @member {Object} properties
 */
Event.prototype.properties = undefined;

/**
 * @member {Number} value
 */
Event.prototype.value = undefined;

/**
 * @member {String} code
 */
Event.prototype.code = undefined;

