/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Feature model module.
 * @module BillaBear/model/Feature
 * @version 1.0.0
 */
export default class Feature {
  /**
   * Constructs a new <code>Feature</code>.
   * @alias module:BillaBear/model/Feature
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Feature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Feature} obj Optional instance to populate.
   * @return {module:BillaBear/model/Feature} The populated <code>Feature</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Feature();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Feature.prototype.id = undefined;

/**
 * @member {String} name
 */
Feature.prototype.name = undefined;

/**
 * @member {String} code
 */
Feature.prototype.code = undefined;

/**
 * @member {String} description
 */
Feature.prototype.description = undefined;

