/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FrontendToken model module.
 * @module BillaBear/model/FrontendToken
 * @version 1.0.0
 */
export default class FrontendToken {
  /**
   * Constructs a new <code>FrontendToken</code>.
   * @alias module:BillaBear/model/FrontendToken
   * @class
   * @param token {String} 
   */
  constructor(token) {
    this.token = token;
  }

  /**
   * Constructs a <code>FrontendToken</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/FrontendToken} obj Optional instance to populate.
   * @return {module:BillaBear/model/FrontendToken} The populated <code>FrontendToken</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FrontendToken();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} token
 */
FrontendToken.prototype.token = undefined;

