/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse400 model module.
 * @module BillaBear/model/InlineResponse400
 * @version 1.0.0
 */
export default class InlineResponse400 {
  /**
   * Constructs a new <code>InlineResponse400</code>.
   * @alias module:BillaBear/model/InlineResponse400
   * @class
   * @param errors {Object.<String, String>} 
   */
  constructor(errors) {
    this.errors = errors;
  }

  /**
   * Constructs a <code>InlineResponse400</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/InlineResponse400} obj Optional instance to populate.
   * @return {module:BillaBear/model/InlineResponse400} The populated <code>InlineResponse400</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse400();
      if (data.hasOwnProperty('errors'))
        obj.errors = ApiClient.convertToType(data['errors'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * @member {Object.<String, String>} errors
 */
InlineResponse400.prototype.errors = undefined;

