/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Cost from './Cost';
import MetricCost from './MetricCost';

/**
 * The InlineResponse2001 model module.
 * @module BillaBear/model/InlineResponse2001
 * @version 1.0.0
 */
export default class InlineResponse2001 {
  /**
   * Constructs a new <code>InlineResponse2001</code>.
   * @alias module:BillaBear/model/InlineResponse2001
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/InlineResponse2001} obj Optional instance to populate.
   * @return {module:BillaBear/model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001();
      if (data.hasOwnProperty('costs'))
        obj.costs = ApiClient.convertToType(data['costs'], [MetricCost]);
      if (data.hasOwnProperty('cost'))
        obj.cost = Cost.constructFromObject(data['cost']);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:BillaBear/model/MetricCost>} costs
 */
InlineResponse2001.prototype.costs = undefined;

/**
 * @member {module:BillaBear/model/Cost} cost
 */
InlineResponse2001.prototype.cost = undefined;

