/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Feature from './Feature';
import Limit from './Limit';

/**
 * The InlineResponse2002 model module.
 * @module BillaBear/model/InlineResponse2002
 * @version 1.0.0
 */
export default class InlineResponse2002 {
  /**
   * Constructs a new <code>InlineResponse2002</code>.
   * @alias module:BillaBear/model/InlineResponse2002
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/InlineResponse2002} obj Optional instance to populate.
   * @return {module:BillaBear/model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002();
      if (data.hasOwnProperty('limits'))
        obj.limits = ApiClient.convertToType(data['limits'], [Limit]);
      if (data.hasOwnProperty('features'))
        obj.features = ApiClient.convertToType(data['features'], [Feature]);
      if (data.hasOwnProperty('user_count'))
        obj.userCount = ApiClient.convertToType(data['user_count'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:BillaBear/model/Limit>} limits
 */
InlineResponse2002.prototype.limits = undefined;

/**
 * @member {Array.<module:BillaBear/model/Feature>} features
 */
InlineResponse2002.prototype.features = undefined;

/**
 * @member {Number} userCount
 */
InlineResponse2002.prototype.userCount = undefined;

