/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InvoiceLines model module.
 * @module BillaBear/model/InvoiceLines
 * @version 1.0.0
 */
export default class InvoiceLines {
  /**
   * Constructs a new <code>InvoiceLines</code>.
   * @alias module:BillaBear/model/InvoiceLines
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InvoiceLines</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/InvoiceLines} obj Optional instance to populate.
   * @return {module:BillaBear/model/InvoiceLines} The populated <code>InvoiceLines</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InvoiceLines();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('sub_total'))
        obj.subTotal = ApiClient.convertToType(data['sub_total'], 'Number');
      if (data.hasOwnProperty('tax_total'))
        obj.taxTotal = ApiClient.convertToType(data['tax_total'], 'Number');
      if (data.hasOwnProperty('tax_rate'))
        obj.taxRate = ApiClient.convertToType(data['tax_rate'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
InvoiceLines.prototype.description = undefined;

/**
 * @member {String} currency
 */
InvoiceLines.prototype.currency = undefined;

/**
 * @member {Number} total
 */
InvoiceLines.prototype.total = undefined;

/**
 * @member {Number} subTotal
 */
InvoiceLines.prototype.subTotal = undefined;

/**
 * @member {Number} taxTotal
 */
InvoiceLines.prototype.taxTotal = undefined;

/**
 * @member {Number} taxRate
 */
InvoiceLines.prototype.taxRate = undefined;

