/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IssueRefundPayment model module.
 * @module BillaBear/model/IssueRefundPayment
 * @version 1.0.0
 */
export default class IssueRefundPayment {
  /**
   * Constructs a new <code>IssueRefundPayment</code>.
   * @alias module:BillaBear/model/IssueRefundPayment
   * @class
   * @param amount {Number} 
   */
  constructor(amount) {
    this.amount = amount;
  }

  /**
   * Constructs a <code>IssueRefundPayment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/IssueRefundPayment} obj Optional instance to populate.
   * @return {module:BillaBear/model/IssueRefundPayment} The populated <code>IssueRefundPayment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IssueRefundPayment();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
IssueRefundPayment.prototype.amount = undefined;

/**
 * Three-letter ISO currency code. Must be upper-case
 * @member {String} currency
 */
IssueRefundPayment.prototype.currency = undefined;

/**
 * @member {String} reason
 */
IssueRefundPayment.prototype.reason = undefined;

