/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Feature from './Feature';

/**
 * The Limit model module.
 * @module BillaBear/model/Limit
 * @version 1.0.0
 */
export default class Limit {
  /**
   * Constructs a new <code>Limit</code>.
   * @alias module:BillaBear/model/Limit
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Limit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Limit} obj Optional instance to populate.
   * @return {module:BillaBear/model/Limit} The populated <code>Limit</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Limit();
      if (data.hasOwnProperty('feature'))
        obj.feature = Feature.constructFromObject(data['feature']);
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:BillaBear/model/Feature} feature
 */
Limit.prototype.feature = undefined;

/**
 * @member {Number} limit
 */
Limit.prototype.limit = undefined;

