/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MetricFilter from './MetricFilter';

/**
 * The Metric model module.
 * @module BillaBear/model/Metric
 * @version 1.0.0
 */
export default class Metric {
  /**
   * Constructs a new <code>Metric</code>.
   * @alias module:BillaBear/model/Metric
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Metric</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Metric} obj Optional instance to populate.
   * @return {module:BillaBear/model/Metric} The populated <code>Metric</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Metric();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('aggregation_method'))
        obj.aggregationMethod = ApiClient.convertToType(data['aggregation_method'], 'String');
      if (data.hasOwnProperty('aggregation_property'))
        obj.aggregationProperty = ApiClient.convertToType(data['aggregation_property'], 'String');
      if (data.hasOwnProperty('filters'))
        obj.filters = ApiClient.convertToType(data['filters'], [MetricFilter]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Metric.prototype.id = undefined;

/**
 * @member {String} name
 */
Metric.prototype.name = undefined;

/**
 * @member {String} code
 */
Metric.prototype.code = undefined;

/**
 * Allowed values for the <code>aggregationMethod</code> property.
 * @enum {String}
 * @readonly
 */
Metric.AggregationMethodEnum = {
  /**
   * value: "count"
   * @const
   */
  count: "count",

  /**
   * value: "sum"
   * @const
   */
  sum: "sum",

  /**
   * value: "latest"
   * @const
   */
  latest: "latest",

  /**
   * value: "unique_count"
   * @const
   */
  uniqueCount: "unique_count",

  /**
   * value: "max"
   * @const
   */
  max: "max"
};
/**
 * @member {module:BillaBear/model/Metric.AggregationMethodEnum} aggregationMethod
 */
Metric.prototype.aggregationMethod = undefined;

/**
 * @member {String} aggregationProperty
 */
Metric.prototype.aggregationProperty = undefined;

/**
 * @member {Array.<module:BillaBear/model/MetricFilter>} filters
 */
Metric.prototype.filters = undefined;

