/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MetricFilter model module.
 * @module BillaBear/model/MetricFilter
 * @version 1.0.0
 */
export default class MetricFilter {
  /**
   * Constructs a new <code>MetricFilter</code>.
   * @alias module:BillaBear/model/MetricFilter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MetricFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/MetricFilter} obj Optional instance to populate.
   * @return {module:BillaBear/model/MetricFilter} The populated <code>MetricFilter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MetricFilter();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
MetricFilter.prototype.id = undefined;

/**
 * @member {String} name
 */
MetricFilter.prototype.name = undefined;

/**
 * @member {String} code
 */
MetricFilter.prototype.code = undefined;

/**
 * @member {String} value
 */
MetricFilter.prototype.value = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
MetricFilter.TypeEnum = {
  /**
   * value: "inclusive"
   * @const
   */
  inclusive: "inclusive",

  /**
   * value: "exclusive"
   * @const
   */
  exclusive: "exclusive"
};
/**
 * @member {module:BillaBear/model/MetricFilter.TypeEnum} type
 */
MetricFilter.prototype.type = undefined;

