/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OneOfSubscriptionMetadata model module.
 * @module BillaBear/model/OneOfSubscriptionMetadata
 * @version 1.0.0
 */
export default class OneOfSubscriptionMetadata {
  /**
   * Constructs a new <code>OneOfSubscriptionMetadata</code>.
   * @alias module:BillaBear/model/OneOfSubscriptionMetadata
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OneOfSubscriptionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/OneOfSubscriptionMetadata} obj Optional instance to populate.
   * @return {module:BillaBear/model/OneOfSubscriptionMetadata} The populated <code>OneOfSubscriptionMetadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfSubscriptionMetadata();
    }
    return obj;
  }
}
