/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ProductTaxType from './ProductTaxType';

/**
 * The Product model module.
 * @module BillaBear/model/Product
 * @version 1.0.0
 */
export default class Product {
  /**
   * Constructs a new <code>Product</code>.
   * @alias module:BillaBear/model/Product
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Product} obj Optional instance to populate.
   * @return {module:BillaBear/model/Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('external_reference'))
        obj.externalReference = ApiClient.convertToType(data['external_reference'], 'String');
      if (data.hasOwnProperty('tax_type'))
        obj.taxType = ProductTaxType.constructFromObject(data['tax_type']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Product.prototype.id = undefined;

/**
 * @member {String} name
 */
Product.prototype.name = undefined;

/**
 * The reference given by the payment provider
 * @member {String} externalReference
 */
Product.prototype.externalReference = undefined;

/**
 * @member {module:BillaBear/model/ProductTaxType} taxType
 */
Product.prototype.taxType = undefined;

