/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductTaxType model module.
 * @module BillaBear/model/ProductTaxType
 * @version 1.0.0
 */
export default class ProductTaxType {
  /**
   * Constructs a new <code>ProductTaxType</code>.
   * @alias module:BillaBear/model/ProductTaxType
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>ProductTaxType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/ProductTaxType} obj Optional instance to populate.
   * @return {module:BillaBear/model/ProductTaxType} The populated <code>ProductTaxType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductTaxType();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('default'))
        obj._default = ApiClient.convertToType(data['default'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ProductTaxType.prototype.id = undefined;

/**
 * @member {String} name
 */
ProductTaxType.prototype.name = undefined;

/**
 * @member {Boolean} _default
 */
ProductTaxType.prototype._default = undefined;

