/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import BillingAdmin from './BillingAdmin';
import Customer from './Customer';
import Paths1paymentgetresponses200contentapplication1jsonschemapropertiesdataitems from './Paths1paymentgetresponses200contentapplication1jsonschemapropertiesdataitems';

/**
 * The Refund model module.
 * @module BillaBear/model/Refund
 * @version 1.0.0
 */
export default class Refund {
  /**
   * Constructs a new <code>Refund</code>.
   * @alias module:BillaBear/model/Refund
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Refund</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Refund} obj Optional instance to populate.
   * @return {module:BillaBear/model/Refund} The populated <code>Refund</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Refund();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('external_reference'))
        obj.externalReference = ApiClient.convertToType(data['external_reference'], 'String');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('payment'))
        obj.payment = Paths1paymentgetresponses200contentapplication1jsonschemapropertiesdataitems.constructFromObject(data['payment']);
      if (data.hasOwnProperty('customer'))
        obj.customer = Customer.constructFromObject(data['customer']);
      if (data.hasOwnProperty('billing_admin'))
        obj.billingAdmin = BillingAdmin.constructFromObject(data['billing_admin']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Refund.prototype.id = undefined;

/**
 * @member {Number} amount
 */
Refund.prototype.amount = undefined;

/**
 * Three-letter ISO currency code. Must be upper-case
 * @member {String} currency
 */
Refund.prototype.currency = undefined;

/**
 * @member {String} externalReference
 */
Refund.prototype.externalReference = undefined;

/**
 * @member {String} comment
 */
Refund.prototype.comment = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Refund.StatusEnum = {
  /**
   * value: "started"
   * @const
   */
  started: "started",

  /**
   * value: "rejected"
   * @const
   */
  rejected: "rejected",

  /**
   * value: "authorised"
   * @const
   */
  authorised: "authorised",

  /**
   * value: "issued"
   * @const
   */
  issued: "issued"
};
/**
 * @member {module:BillaBear/model/Refund.StatusEnum} status
 */
Refund.prototype.status = undefined;

/**
 * @member {String} createdAt
 */
Refund.prototype.createdAt = undefined;

/**
 * @member {module:BillaBear/model/Paths1paymentgetresponses200contentapplication1jsonschemapropertiesdataitems} payment
 */
Refund.prototype.payment = undefined;

/**
 * @member {module:BillaBear/model/Customer} customer
 */
Refund.prototype.customer = undefined;

/**
 * @member {module:BillaBear/model/BillingAdmin} billingAdmin
 */
Refund.prototype.billingAdmin = undefined;

