/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Price from './Price';
import SubscriptionPlan from './SubscriptionPlan';

/**
 * The Subscription model module.
 * @module BillaBear/model/Subscription
 * @version 1.0.0
 */
export default class Subscription {
  /**
   * Constructs a new <code>Subscription</code>.
   * @alias module:BillaBear/model/Subscription
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Subscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/Subscription} obj Optional instance to populate.
   * @return {module:BillaBear/model/Subscription} The populated <code>Subscription</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Subscription();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('seat_number'))
        obj.seatNumber = ApiClient.convertToType(data['seat_number'], 'Number');
      if (data.hasOwnProperty('schedule'))
        obj.schedule = ApiClient.convertToType(data['schedule'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'String');
      if (data.hasOwnProperty('ended_at'))
        obj.endedAt = ApiClient.convertToType(data['ended_at'], 'String');
      if (data.hasOwnProperty('valid_until'))
        obj.validUntil = ApiClient.convertToType(data['valid_until'], 'String');
      if (data.hasOwnProperty('main_external_reference'))
        obj.mainExternalReference = ApiClient.convertToType(data['main_external_reference'], 'String');
      if (data.hasOwnProperty('child_external_reference'))
        obj.childExternalReference = ApiClient.convertToType(data['child_external_reference'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = Price.constructFromObject(data['price']);
      if (data.hasOwnProperty('plan'))
        obj.plan = SubscriptionPlan.constructFromObject(data['plan']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Subscription.prototype.id = undefined;

/**
 * @member {Number} seatNumber
 */
Subscription.prototype.seatNumber = undefined;

/**
 * @member {String} schedule
 */
Subscription.prototype.schedule = undefined;

/**
 * @member {String} status
 */
Subscription.prototype.status = undefined;

/**
 * @member {String} createdAt
 */
Subscription.prototype.createdAt = undefined;

/**
 * @member {String} updatedAt
 */
Subscription.prototype.updatedAt = undefined;

/**
 * @member {String} endedAt
 */
Subscription.prototype.endedAt = undefined;

/**
 * @member {String} validUntil
 */
Subscription.prototype.validUntil = undefined;

/**
 * @member {String} mainExternalReference
 */
Subscription.prototype.mainExternalReference = undefined;

/**
 * @member {String} childExternalReference
 */
Subscription.prototype.childExternalReference = undefined;

/**
 * @member {module:BillaBear/model/Price} price
 */
Subscription.prototype.price = undefined;

/**
 * @member {module:BillaBear/model/SubscriptionPlan} plan
 */
Subscription.prototype.plan = undefined;

