/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SubscriptionIdCancelBody model module.
 * @module BillaBear/model/SubscriptionIdCancelBody
 * @version 1.0.0
 */
export default class SubscriptionIdCancelBody {
  /**
   * Constructs a new <code>SubscriptionIdCancelBody</code>.
   * @alias module:BillaBear/model/SubscriptionIdCancelBody
   * @class
   * @param when {module:BillaBear/model/SubscriptionIdCancelBody.WhenEnum} 
   * @param refundType {module:BillaBear/model/SubscriptionIdCancelBody.RefundTypeEnum} 
   */
  constructor(when, refundType) {
    this.when = when;
    this.refundType = refundType;
  }

  /**
   * Constructs a <code>SubscriptionIdCancelBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/SubscriptionIdCancelBody} obj Optional instance to populate.
   * @return {module:BillaBear/model/SubscriptionIdCancelBody} The populated <code>SubscriptionIdCancelBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionIdCancelBody();
      if (data.hasOwnProperty('when'))
        obj.when = ApiClient.convertToType(data['when'], 'String');
      if (data.hasOwnProperty('refund_type'))
        obj.refundType = ApiClient.convertToType(data['refund_type'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>when</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionIdCancelBody.WhenEnum = {
  /**
   * value: "end-of-run"
   * @const
   */
  endOfRun: "end-of-run",

  /**
   * value: "instantly"
   * @const
   */
  instantly: "instantly",

  /**
   * value: "specific-date"
   * @const
   */
  specificDate: "specific-date"
};
/**
 * @member {module:BillaBear/model/SubscriptionIdCancelBody.WhenEnum} when
 * @default 'end-of-run'
 */
SubscriptionIdCancelBody.prototype.when = 'end-of-run';

/**
 * Allowed values for the <code>refundType</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionIdCancelBody.RefundTypeEnum = {
  /**
   * value: "none"
   * @const
   */
  none: "none",

  /**
   * value: "full"
   * @const
   */
  full: "full",

  /**
   * value: "prorate"
   * @const
   */
  prorate: "prorate"
};
/**
 * @member {module:BillaBear/model/SubscriptionIdCancelBody.RefundTypeEnum} refundType
 * @default 'none'
 */
SubscriptionIdCancelBody.prototype.refundType = 'none';

/**
 * @member {Date} _date
 */
SubscriptionIdCancelBody.prototype._date = undefined;

/**
 * @member {String} comment
 */
SubscriptionIdCancelBody.prototype.comment = undefined;

