/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Uuid from './Uuid';

/**
 * The SubscriptionIdExtendBody model module.
 * @module BillaBear/model/SubscriptionIdExtendBody
 * @version 1.0.0
 */
export default class SubscriptionIdExtendBody {
  /**
   * Constructs a new <code>SubscriptionIdExtendBody</code>.
   * @alias module:BillaBear/model/SubscriptionIdExtendBody
   * @class
   * @param price {module:BillaBear/model/Uuid} 
   */
  constructor(price) {
    this.price = price;
  }

  /**
   * Constructs a <code>SubscriptionIdExtendBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/SubscriptionIdExtendBody} obj Optional instance to populate.
   * @return {module:BillaBear/model/SubscriptionIdExtendBody} The populated <code>SubscriptionIdExtendBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionIdExtendBody();
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], Uuid);
    }
    return obj;
  }
}

/**
 * @member {module:BillaBear/model/Uuid} price
 */
SubscriptionIdExtendBody.prototype.price = undefined;

