/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Feature from './Feature';
import Limit from './Limit';
import Price from './Price';
import Product from './Product';

/**
 * The SubscriptionPlan model module.
 * @module BillaBear/model/SubscriptionPlan
 * @version 1.0.0
 */
export default class SubscriptionPlan {
  /**
   * Constructs a new <code>SubscriptionPlan</code>.
   * @alias module:BillaBear/model/SubscriptionPlan
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SubscriptionPlan</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/SubscriptionPlan} obj Optional instance to populate.
   * @return {module:BillaBear/model/SubscriptionPlan} The populated <code>SubscriptionPlan</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionPlan();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code_name'))
        obj.codeName = ApiClient.convertToType(data['code_name'], 'String');
      if (data.hasOwnProperty('user_count'))
        obj.userCount = ApiClient.convertToType(data['user_count'], 'Number');
      if (data.hasOwnProperty('per_seat'))
        obj.perSeat = ApiClient.convertToType(data['per_seat'], 'Boolean');
      if (data.hasOwnProperty('has_trial'))
        obj.hasTrial = ApiClient.convertToType(data['has_trial'], 'Boolean');
      if (data.hasOwnProperty('is_trial_standalone'))
        obj.isTrialStandalone = ApiClient.convertToType(data['is_trial_standalone'], 'Boolean');
      if (data.hasOwnProperty('free'))
        obj.free = ApiClient.convertToType(data['free'], 'Boolean');
      if (data.hasOwnProperty('public'))
        obj._public = ApiClient.convertToType(data['public'], 'Boolean');
      if (data.hasOwnProperty('limits'))
        obj.limits = ApiClient.convertToType(data['limits'], [Limit]);
      if (data.hasOwnProperty('features'))
        obj.features = ApiClient.convertToType(data['features'], [Feature]);
      if (data.hasOwnProperty('product'))
        obj.product = Product.constructFromObject(data['product']);
      if (data.hasOwnProperty('prices'))
        obj.prices = ApiClient.convertToType(data['prices'], [Price]);
      if (data.hasOwnProperty('trial_length_days'))
        obj.trialLengthDays = ApiClient.convertToType(data['trial_length_days'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
SubscriptionPlan.prototype.id = undefined;

/**
 * @member {String} name
 */
SubscriptionPlan.prototype.name = undefined;

/**
 * @member {String} codeName
 */
SubscriptionPlan.prototype.codeName = undefined;

/**
 * @member {Number} userCount
 */
SubscriptionPlan.prototype.userCount = undefined;

/**
 * @member {Boolean} perSeat
 */
SubscriptionPlan.prototype.perSeat = undefined;

/**
 * @member {Boolean} hasTrial
 */
SubscriptionPlan.prototype.hasTrial = undefined;

/**
 * @member {Boolean} isTrialStandalone
 */
SubscriptionPlan.prototype.isTrialStandalone = undefined;

/**
 * @member {Boolean} free
 */
SubscriptionPlan.prototype.free = undefined;

/**
 * @member {Boolean} _public
 */
SubscriptionPlan.prototype._public = undefined;

/**
 * @member {Array.<module:BillaBear/model/Limit>} limits
 */
SubscriptionPlan.prototype.limits = undefined;

/**
 * @member {Array.<module:BillaBear/model/Feature>} features
 */
SubscriptionPlan.prototype.features = undefined;

/**
 * @member {module:BillaBear/model/Product} product
 */
SubscriptionPlan.prototype.product = undefined;

/**
 * @member {Array.<module:BillaBear/model/Price>} prices
 */
SubscriptionPlan.prototype.prices = undefined;

/**
 * @member {Number} trialLengthDays
 */
SubscriptionPlan.prototype.trialLengthDays = undefined;

