/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Uuid from './Uuid';

/**
 * The SubscriptionIdPriceBody model module.
 * @module BillaBear/model/SubscriptionIdPriceBody
 * @version 1.0.0
 */
export default class SubscriptionIdPriceBody {
  /**
   * Constructs a new <code>SubscriptionIdPriceBody</code>.
   * @alias module:BillaBear/model/SubscriptionIdPriceBody
   * @class
   * @param price {module:BillaBear/model/Uuid} 
   * @param when {module:BillaBear/model/SubscriptionIdPriceBody.WhenEnum} 
   */
  constructor(price, when) {
    this.price = price;
    this.when = when;
  }

  /**
   * Constructs a <code>SubscriptionIdPriceBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/SubscriptionIdPriceBody} obj Optional instance to populate.
   * @return {module:BillaBear/model/SubscriptionIdPriceBody} The populated <code>SubscriptionIdPriceBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionIdPriceBody();
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], Uuid);
      if (data.hasOwnProperty('when'))
        obj.when = ApiClient.convertToType(data['when'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:BillaBear/model/Uuid} price
 */
SubscriptionIdPriceBody.prototype.price = undefined;

/**
 * Allowed values for the <code>when</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionIdPriceBody.WhenEnum = {
  /**
   * value: "next_cycle"
   * @const
   */
  nextCycle: "next_cycle",

  /**
   * value: "instantly"
   * @const
   */
  instantly: "instantly"
};
/**
 * @member {module:BillaBear/model/SubscriptionIdPriceBody.WhenEnum} when
 */
SubscriptionIdPriceBody.prototype.when = undefined;

