/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SubscriptionTrialBody model module.
 * @module BillaBear/model/SubscriptionTrialBody
 * @version 1.0.0
 */
export default class SubscriptionTrialBody {
  /**
   * Constructs a new <code>SubscriptionTrialBody</code>.
   * @alias module:BillaBear/model/SubscriptionTrialBody
   * @class
   * @param subscriptionPlan {String} The ID for the subscription plan to be used (Can also be the code name)
   */
  constructor(subscriptionPlan) {
    this.subscriptionPlan = subscriptionPlan;
  }

  /**
   * Constructs a <code>SubscriptionTrialBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/SubscriptionTrialBody} obj Optional instance to populate.
   * @return {module:BillaBear/model/SubscriptionTrialBody} The populated <code>SubscriptionTrialBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionTrialBody();
      if (data.hasOwnProperty('subscription_plan'))
        obj.subscriptionPlan = ApiClient.convertToType(data['subscription_plan'], 'String');
      if (data.hasOwnProperty('card_token'))
        obj.cardToken = ApiClient.convertToType(data['card_token'], 'String');
      if (data.hasOwnProperty('seat_numbrers'))
        obj.seatNumbrers = ApiClient.convertToType(data['seat_numbrers'], 'Number');
      if (data.hasOwnProperty('trial_length_days'))
        obj.trialLengthDays = ApiClient.convertToType(data['trial_length_days'], 'Number');
    }
    return obj;
  }
}

/**
 * The ID for the subscription plan to be used (Can also be the code name)
 * @member {String} subscriptionPlan
 */
SubscriptionTrialBody.prototype.subscriptionPlan = undefined;

/**
 * A stripe card token that's been created using Stripe's js sdk. It'll create the payment details for the customer.
 * @member {String} cardToken
 */
SubscriptionTrialBody.prototype.cardToken = undefined;

/**
 * @member {Number} seatNumbrers
 */
SubscriptionTrialBody.prototype.seatNumbrers = undefined;

/**
 * @member {Number} trialLengthDays
 */
SubscriptionTrialBody.prototype.trialLengthDays = undefined;

