/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UsageLimit model module.
 * @module BillaBear/model/UsageLimit
 * @version 1.0.0
 */
export default class UsageLimit {
  /**
   * Constructs a new <code>UsageLimit</code>.
   * @alias module:BillaBear/model/UsageLimit
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UsageLimit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/UsageLimit} obj Optional instance to populate.
   * @return {module:BillaBear/model/UsageLimit} The populated <code>UsageLimit</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UsageLimit();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('action'))
        obj.action = ApiClient.convertToType(data['action'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UsageLimit.prototype.id = undefined;

/**
 * @member {Number} amount
 */
UsageLimit.prototype.amount = undefined;

/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
UsageLimit.ActionEnum = {
  /**
   * value: "WARNING"
   * @const
   */
  WARNING: "WARNING",

  /**
   * value: "DISABLE"
   * @const
   */
  DISABLE: "DISABLE"
};
/**
 * @member {module:BillaBear/model/UsageLimit.ActionEnum} action
 */
UsageLimit.prototype.action = undefined;

