/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The VoucherCode model module.
 * @module BillaBear/model/VoucherCode
 * @version 1.0.0
 */
export default class VoucherCode {
  /**
   * Constructs a new <code>VoucherCode</code>.
   * @alias module:BillaBear/model/VoucherCode
   * @class
   * @param code {String} 
   */
  constructor(code) {
    this.code = code;
  }

  /**
   * Constructs a <code>VoucherCode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:BillaBear/model/VoucherCode} obj Optional instance to populate.
   * @return {module:BillaBear/model/VoucherCode} The populated <code>VoucherCode</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VoucherCode();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
VoucherCode.prototype.code = undefined;

