/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Address from './model/Address';
import BillingAdmin from './model/BillingAdmin';
import CheckoutBody from './model/CheckoutBody';
import CheckoutItems from './model/CheckoutItems';
import CheckoutSubscriptions from './model/CheckoutSubscriptions';
import Customer from './model/Customer';
import Error from './model/Error';
import Feature from './model/Feature';
import FrontendToken from './model/FrontendToken';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse20010 from './model/InlineResponse20010';
import InlineResponse20011 from './model/InlineResponse20011';
import InlineResponse20012 from './model/InlineResponse20012';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2007Data from './model/InlineResponse2007Data';
import InlineResponse2007Receipts from './model/InlineResponse2007Receipts';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse201 from './model/InlineResponse201';
import InlineResponse201Lines from './model/InlineResponse201Lines';
import InlineResponse400 from './model/InlineResponse400';
import Invoice from './model/Invoice';
import InvoiceLines from './model/InvoiceLines';
import IssueRefundPayment from './model/IssueRefundPayment';
import Limit from './model/Limit';
import PaymentDetails from './model/PaymentDetails';
import Price from './model/Price';
import Product from './model/Product';
import ProductTaxType from './model/ProductTaxType';
import Refund from './model/Refund';
import SeatsAddBody from './model/SeatsAddBody';
import SeatsRemoveBody from './model/SeatsRemoveBody';
import Subscription from './model/Subscription';
import SubscriptionIdCancelBody from './model/SubscriptionIdCancelBody';
import SubscriptionIdExtendBody from './model/SubscriptionIdExtendBody';
import SubscriptionIdPlanBody from './model/SubscriptionIdPlanBody';
import SubscriptionIdPriceBody from './model/SubscriptionIdPriceBody';
import SubscriptionPlan from './model/SubscriptionPlan';
import SubscriptionStartBody from './model/SubscriptionStartBody';
import SubscriptionTrialBody from './model/SubscriptionTrialBody';
import VoucherCode from './model/VoucherCode';
import CheckoutApi from './api/CheckoutApi';
import CustomersApi from './api/CustomersApi';
import InvoicesApi from './api/InvoicesApi';
import PaymentDetailsApi from './api/PaymentDetailsApi';
import PaymentsApi from './api/PaymentsApi';
import PricesApi from './api/PricesApi';
import ProductsApi from './api/ProductsApi';
import ReceiptApi from './api/ReceiptApi';
import RefundsApi from './api/RefundsApi';
import SubscriptionsApi from './api/SubscriptionsApi';

/**
* The_REST_API_provided_by_BillaBear.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BillaBear = require('BillaBear/index'); // See note below*.
* var xxxSvc = new BillaBear.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BillaBear.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['BillaBear/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BillaBear.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BillaBear.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module BillaBear/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:BillaBear/ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:BillaBear/model/Address}
     */
    Address,

    /**
     * The BillingAdmin model constructor.
     * @property {module:BillaBear/model/BillingAdmin}
     */
    BillingAdmin,

    /**
     * The CheckoutBody model constructor.
     * @property {module:BillaBear/model/CheckoutBody}
     */
    CheckoutBody,

    /**
     * The CheckoutItems model constructor.
     * @property {module:BillaBear/model/CheckoutItems}
     */
    CheckoutItems,

    /**
     * The CheckoutSubscriptions model constructor.
     * @property {module:BillaBear/model/CheckoutSubscriptions}
     */
    CheckoutSubscriptions,

    /**
     * The Customer model constructor.
     * @property {module:BillaBear/model/Customer}
     */
    Customer,

    /**
     * The Error model constructor.
     * @property {module:BillaBear/model/Error}
     */
    Error,

    /**
     * The Feature model constructor.
     * @property {module:BillaBear/model/Feature}
     */
    Feature,

    /**
     * The FrontendToken model constructor.
     * @property {module:BillaBear/model/FrontendToken}
     */
    FrontendToken,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:BillaBear/model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:BillaBear/model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:BillaBear/model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:BillaBear/model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:BillaBear/model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:BillaBear/model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:BillaBear/model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:BillaBear/model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:BillaBear/model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:BillaBear/model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:BillaBear/model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2007Data model constructor.
     * @property {module:BillaBear/model/InlineResponse2007Data}
     */
    InlineResponse2007Data,

    /**
     * The InlineResponse2007Receipts model constructor.
     * @property {module:BillaBear/model/InlineResponse2007Receipts}
     */
    InlineResponse2007Receipts,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:BillaBear/model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:BillaBear/model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:BillaBear/model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The InlineResponse201Lines model constructor.
     * @property {module:BillaBear/model/InlineResponse201Lines}
     */
    InlineResponse201Lines,

    /**
     * The InlineResponse400 model constructor.
     * @property {module:BillaBear/model/InlineResponse400}
     */
    InlineResponse400,

    /**
     * The Invoice model constructor.
     * @property {module:BillaBear/model/Invoice}
     */
    Invoice,

    /**
     * The InvoiceLines model constructor.
     * @property {module:BillaBear/model/InvoiceLines}
     */
    InvoiceLines,

    /**
     * The IssueRefundPayment model constructor.
     * @property {module:BillaBear/model/IssueRefundPayment}
     */
    IssueRefundPayment,

    /**
     * The Limit model constructor.
     * @property {module:BillaBear/model/Limit}
     */
    Limit,

    /**
     * The PaymentDetails model constructor.
     * @property {module:BillaBear/model/PaymentDetails}
     */
    PaymentDetails,

    /**
     * The Price model constructor.
     * @property {module:BillaBear/model/Price}
     */
    Price,

    /**
     * The Product model constructor.
     * @property {module:BillaBear/model/Product}
     */
    Product,

    /**
     * The ProductTaxType model constructor.
     * @property {module:BillaBear/model/ProductTaxType}
     */
    ProductTaxType,

    /**
     * The Refund model constructor.
     * @property {module:BillaBear/model/Refund}
     */
    Refund,

    /**
     * The SeatsAddBody model constructor.
     * @property {module:BillaBear/model/SeatsAddBody}
     */
    SeatsAddBody,

    /**
     * The SeatsRemoveBody model constructor.
     * @property {module:BillaBear/model/SeatsRemoveBody}
     */
    SeatsRemoveBody,

    /**
     * The Subscription model constructor.
     * @property {module:BillaBear/model/Subscription}
     */
    Subscription,

    /**
     * The SubscriptionIdCancelBody model constructor.
     * @property {module:BillaBear/model/SubscriptionIdCancelBody}
     */
    SubscriptionIdCancelBody,

    /**
     * The SubscriptionIdExtendBody model constructor.
     * @property {module:BillaBear/model/SubscriptionIdExtendBody}
     */
    SubscriptionIdExtendBody,

    /**
     * The SubscriptionIdPlanBody model constructor.
     * @property {module:BillaBear/model/SubscriptionIdPlanBody}
     */
    SubscriptionIdPlanBody,

    /**
     * The SubscriptionIdPriceBody model constructor.
     * @property {module:BillaBear/model/SubscriptionIdPriceBody}
     */
    SubscriptionIdPriceBody,

    /**
     * The SubscriptionPlan model constructor.
     * @property {module:BillaBear/model/SubscriptionPlan}
     */
    SubscriptionPlan,

    /**
     * The SubscriptionStartBody model constructor.
     * @property {module:BillaBear/model/SubscriptionStartBody}
     */
    SubscriptionStartBody,

    /**
     * The SubscriptionTrialBody model constructor.
     * @property {module:BillaBear/model/SubscriptionTrialBody}
     */
    SubscriptionTrialBody,

    /**
     * The VoucherCode model constructor.
     * @property {module:BillaBear/model/VoucherCode}
     */
    VoucherCode,

    /**
    * The CheckoutApi service constructor.
    * @property {module:BillaBear/api/CheckoutApi}
    */
    CheckoutApi,

    /**
    * The CustomersApi service constructor.
    * @property {module:BillaBear/api/CustomersApi}
    */
    CustomersApi,

    /**
    * The InvoicesApi service constructor.
    * @property {module:BillaBear/api/InvoicesApi}
    */
    InvoicesApi,

    /**
    * The PaymentDetailsApi service constructor.
    * @property {module:BillaBear/api/PaymentDetailsApi}
    */
    PaymentDetailsApi,

    /**
    * The PaymentsApi service constructor.
    * @property {module:BillaBear/api/PaymentsApi}
    */
    PaymentsApi,

    /**
    * The PricesApi service constructor.
    * @property {module:BillaBear/api/PricesApi}
    */
    PricesApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:BillaBear/api/ProductsApi}
    */
    ProductsApi,

    /**
    * The ReceiptApi service constructor.
    * @property {module:BillaBear/api/ReceiptApi}
    */
    ReceiptApi,

    /**
    * The RefundsApi service constructor.
    * @property {module:BillaBear/api/RefundsApi}
    */
    RefundsApi,

    /**
    * The SubscriptionsApi service constructor.
    * @property {module:BillaBear/api/SubscriptionsApi}
    */
    SubscriptionsApi
};
