/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Error from '../model/Error';
import InlineResponse20014 from '../model/InlineResponse20014';
import InlineResponse2004 from '../model/InlineResponse2004';
import InlineResponse2006 from '../model/InlineResponse2006';
import InlineResponse2009 from '../model/InlineResponse2009';
import IssueRefundPayment from '../model/IssueRefundPayment';

/**
* Payments service.
* @module BillaBear/api/PaymentsApi
* @version 1.0.0
*/
export default class PaymentsApi {

    /**
    * Constructs a new PaymentsApi. 
    * @alias module:BillaBear/api/PaymentsApi
    * @class
    * @param {module:BillaBear/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:BillaBear/ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the chargeInvoice operation.
     * @callback moduleBillaBear/api/PaymentsApi~chargeInvoiceCallback
     * @param {String} error Error message, if any.
     * @param {module:BillaBear/model/InlineResponse20014{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Charge Invoice
     * Attempts to charge a card that is on file for the invoice amount
     * @param {String} invoiceId The id of the invoice
     * @param {module:BillaBear/api/PaymentsApi~chargeInvoiceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    chargeInvoice(invoiceId, callback) {
      
      let postBody = null;
      // verify the required parameter 'invoiceId' is set
      if (invoiceId === undefined || invoiceId === null) {
        throw new Error("Missing the required parameter 'invoiceId' when calling chargeInvoice");
      }

      let pathParams = {
        'invoiceId': invoiceId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20014;

      return this.apiClient.callApi(
        '/invoice/{invoiceId}/charge', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the downloadInvoice operation.
     * @callback moduleBillaBear/api/PaymentsApi~downloadInvoiceCallback
     * @param {String} error Error message, if any.
     * @param {'Blob'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download Invoice
     * Returns the pdf blob for the invoice
     * @param {String} invoiceId The id of the invoice
     * @param {module:BillaBear/api/PaymentsApi~downloadInvoiceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    downloadInvoice(invoiceId, callback) {
      
      let postBody = null;
      // verify the required parameter 'invoiceId' is set
      if (invoiceId === undefined || invoiceId === null) {
        throw new Error("Missing the required parameter 'invoiceId' when calling downloadInvoice");
      }

      let pathParams = {
        'invoiceId': invoiceId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/pdf'];
      let returnType = 'Blob';

      return this.apiClient.callApi(
        '/invoice/{invoiceId}/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the downloadReceipt operation.
     * @callback moduleBillaBear/api/PaymentsApi~downloadReceiptCallback
     * @param {String} error Error message, if any.
     * @param {'Blob'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download Receipt
     * Returns the pdf blob for the Receipt
     * @param {String} receipt The id of the receipt
     * @param {module:BillaBear/api/PaymentsApi~downloadReceiptCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    downloadReceipt(receipt, callback) {
      
      let postBody = null;
      // verify the required parameter 'receipt' is set
      if (receipt === undefined || receipt === null) {
        throw new Error("Missing the required parameter 'receipt' when calling downloadReceipt");
      }

      let pathParams = {
        'receipt': receipt
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/pdf'];
      let returnType = 'Blob';

      return this.apiClient.callApi(
        '/receipt/{receiptId}/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getInvoicesForCustomer operation.
     * @callback moduleBillaBear/api/PaymentsApi~getInvoicesForCustomerCallback
     * @param {String} error Error message, if any.
     * @param {module:BillaBear/model/InlineResponse2006{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Customer Invoices
     * List Customer Invoices
     * @param {String} customerId The id of the customer to retrieve
     * @param {module:BillaBear/api/PaymentsApi~getInvoicesForCustomerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getInvoicesForCustomer(customerId, callback) {
      
      let postBody = null;
      // verify the required parameter 'customerId' is set
      if (customerId === undefined || customerId === null) {
        throw new Error("Missing the required parameter 'customerId' when calling getInvoicesForCustomer");
      }

      let pathParams = {
        'customerId': customerId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2006;

      return this.apiClient.callApi(
        '/customer/{customerId}/invoices', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getPaymentsForCustomer operation.
     * @callback moduleBillaBear/api/PaymentsApi~getPaymentsForCustomerCallback
     * @param {String} error Error message, if any.
     * @param {module:BillaBear/model/InlineResponse2004{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Customer Payments
     * List Customer Payment
     * @param {String} customerId The id of the customer to retrieve
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit How many items to return at one time (max 100)
     * @param {String} opts.lastKey The key to be used in pagination to say what the last key of the previous page was
     * @param {String} opts.name The name to search for
     * @param {module:BillaBear/api/PaymentsApi~getPaymentsForCustomerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getPaymentsForCustomer(customerId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'customerId' is set
      if (customerId === undefined || customerId === null) {
        throw new Error("Missing the required parameter 'customerId' when calling getPaymentsForCustomer");
      }

      let pathParams = {
        'customerId': customerId
      };
      let queryParams = {
        'limit': opts['limit'],'last_key': opts['lastKey'],'name': opts['name']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2004;

      return this.apiClient.callApi(
        '/customer/{customerId}/payment', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listPayment operation.
     * @callback moduleBillaBear/api/PaymentsApi~listPaymentCallback
     * @param {String} error Error message, if any.
     * @param {module:BillaBear/model/InlineResponse2009{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List
     * List all payment
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit How many items to return at one time (max 100)
     * @param {String} opts.lastKey The key to be used in pagination to say what the last key of the previous page was
     * @param {String} opts.name The name to search for
     * @param {module:BillaBear/api/PaymentsApi~listPaymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listPayment(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'limit': opts['limit'],'last_key': opts['lastKey'],'name': opts['name']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2009;

      return this.apiClient.callApi(
        '/payment', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the refundPayment operation.
     * @callback moduleBillaBear/api/PaymentsApi~refundPaymentCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Refund Payment
     * Issue a refund for payment
     * @param {module:BillaBear/model/IssueRefundPayment} body 
     * @param {String} paymentId The id of the payment
     * @param {module:BillaBear/api/PaymentsApi~refundPaymentCallback} callback The callback function, accepting three arguments: error, data, response
     */
    refundPayment(body, paymentId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling refundPayment");
      }
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling refundPayment");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/payment/{paymentId}/refund', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}