/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";

/**
* Receipt service.
* @module BillaBear/api/ReceiptApi
* @version 1.0.0
*/
export default class ReceiptApi {

    /**
    * Constructs a new ReceiptApi. 
    * @alias module:BillaBear/api/ReceiptApi
    * @class
    * @param {module:BillaBear/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:BillaBear/ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the downloadReceipt operation.
     * @callback moduleBillaBear/api/ReceiptApi~downloadReceiptCallback
     * @param {String} error Error message, if any.
     * @param {'Blob'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download Receipt
     * Returns the pdf blob for the Receipt
     * @param {String} receipt The id of the receipt
     * @param {module:BillaBear/api/ReceiptApi~downloadReceiptCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    downloadReceipt(receipt, callback) {
      
      let postBody = null;
      // verify the required parameter 'receipt' is set
      if (receipt === undefined || receipt === null) {
        throw new Error("Missing the required parameter 'receipt' when calling downloadReceipt");
      }

      let pathParams = {
        'receipt': receipt
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/pdf'];
      let returnType = 'Blob';

      return this.apiClient.callApi(
        '/receipt/{receiptId}/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}