/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/BillaBear/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/BillaBear/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillaBear);
  }
}(this, function(expect, BillaBear) {
  'use strict';

  var instance;

  describe('BillaBear', function() {
    describe('PaymentDetails', function() {
      beforeEach(function() {
        instance = new BillaBear.PaymentDetails();
      });

      it('should create an instance of PaymentDetails', function() {
        // TODO: update the code to test PaymentDetails
        expect(instance).to.be.a(BillaBear.PaymentDetails);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property _default (base name: "default")', function() {
        // TODO: update the code to test the property _default
        expect(instance).to.have.property('_default');
        // expect(instance._default).to.be(expectedValueLiteral);
      });

      it('should have the property brand (base name: "brand")', function() {
        // TODO: update the code to test the property brand
        expect(instance).to.have.property('brand');
        // expect(instance.brand).to.be(expectedValueLiteral);
      });

      it('should have the property lastFour (base name: "last_four")', function() {
        // TODO: update the code to test the property lastFour
        expect(instance).to.have.property('lastFour');
        // expect(instance.lastFour).to.be(expectedValueLiteral);
      });

      it('should have the property expiryMonth (base name: "expiry_month")', function() {
        // TODO: update the code to test the property expiryMonth
        expect(instance).to.have.property('expiryMonth');
        // expect(instance.expiryMonth).to.be(expectedValueLiteral);
      });

      it('should have the property expiryYear (base name: "expiry_year")', function() {
        // TODO: update the code to test the property expiryYear
        expect(instance).to.have.property('expiryYear');
        // expect(instance.expiryYear).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
