/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/BillaBear/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/BillaBear/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillaBear);
  }
}(this, function(expect, BillaBear) {
  'use strict';

  var instance;

  describe('BillaBear', function() {
    describe('SubscriptionTrialBody', function() {
      beforeEach(function() {
        instance = new BillaBear.SubscriptionTrialBody();
      });

      it('should create an instance of SubscriptionTrialBody', function() {
        // TODO: update the code to test SubscriptionTrialBody
        expect(instance).to.be.a(BillaBear.SubscriptionTrialBody);
      });

      it('should have the property subscriptionPlan (base name: "subscription_plan")', function() {
        // TODO: update the code to test the property subscriptionPlan
        expect(instance).to.have.property('subscriptionPlan');
        // expect(instance.subscriptionPlan).to.be(expectedValueLiteral);
      });

      it('should have the property cardToken (base name: "card_token")', function() {
        // TODO: update the code to test the property cardToken
        expect(instance).to.have.property('cardToken');
        // expect(instance.cardToken).to.be(expectedValueLiteral);
      });

      it('should have the property seatNumbrers (base name: "seat_numbrers")', function() {
        // TODO: update the code to test the property seatNumbrers
        expect(instance).to.have.property('seatNumbrers');
        // expect(instance.seatNumbrers).to.be(expectedValueLiteral);
      });

      it('should have the property trialLengthDays (base name: "trial_length_days")', function() {
        // TODO: update the code to test the property trialLengthDays
        expect(instance).to.have.property('trialLengthDays');
        // expect(instance.trialLengthDays).to.be(expectedValueLiteral);
      });

    });
  });

}));
