/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/BillaBear/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/BillaBear/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillaBear);
  }
}(this, function(expect, BillaBear) {
  'use strict';

  var instance;

  describe('BillaBear', function() {
    describe('Subscription', function() {
      beforeEach(function() {
        instance = new BillaBear.Subscription();
      });

      it('should create an instance of Subscription', function() {
        // TODO: update the code to test Subscription
        expect(instance).to.be.a(BillaBear.Subscription);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property seatNumber (base name: "seat_number")', function() {
        // TODO: update the code to test the property seatNumber
        expect(instance).to.have.property('seatNumber');
        // expect(instance.seatNumber).to.be(expectedValueLiteral);
      });

      it('should have the property schedule (base name: "schedule")', function() {
        // TODO: update the code to test the property schedule
        expect(instance).to.have.property('schedule');
        // expect(instance.schedule).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updated_at")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property endedAt (base name: "ended_at")', function() {
        // TODO: update the code to test the property endedAt
        expect(instance).to.have.property('endedAt');
        // expect(instance.endedAt).to.be(expectedValueLiteral);
      });

      it('should have the property validUntil (base name: "valid_until")', function() {
        // TODO: update the code to test the property validUntil
        expect(instance).to.have.property('validUntil');
        // expect(instance.validUntil).to.be(expectedValueLiteral);
      });

      it('should have the property mainExternalReference (base name: "main_external_reference")', function() {
        // TODO: update the code to test the property mainExternalReference
        expect(instance).to.have.property('mainExternalReference');
        // expect(instance.mainExternalReference).to.be(expectedValueLiteral);
      });

      it('should have the property childExternalReference (base name: "child_external_reference")', function() {
        // TODO: update the code to test the property childExternalReference
        expect(instance).to.have.property('childExternalReference');
        // expect(instance.childExternalReference).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property plan (base name: "plan")', function() {
        // TODO: update the code to test the property plan
        expect(instance).to.have.property('plan');
        // expect(instance.plan).to.be(expectedValueLiteral);
      });

    });
  });

}));
