/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/BillaBear/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/BillaBear/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillaBear);
  }
}(this, function(expect, BillaBear) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BillaBear.PaymentDetailsApi();
  });

  describe('BillaBear', function() {
    describe('PaymentDetailsApi', function() {
      describe('completeFrontendPaymentDetails', function() {
        it('should call completeFrontendPaymentDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for completeFrontendPaymentDetails call and complete the assertions
          /*

          instance.completeFrontendPaymentDetails(body, customerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BillaBear.PaymentDetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePaymentDetails', function() {
        it('should call deletePaymentDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePaymentDetails call and complete the assertions
          /*

          instance.deletePaymentDetails(paymentDetailsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePaymentDetailsCustomer', function() {
        it('should call deletePaymentDetailsCustomer successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePaymentDetailsCustomer call and complete the assertions
          /*

          instance.deletePaymentDetailsCustomer(customerId, paymentDetailsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPaymentDetails', function() {
        it('should call getPaymentDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for getPaymentDetails call and complete the assertions
          /*

          instance.getPaymentDetails(paymentDetailsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BillaBear.PaymentDetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listPaymentDetails', function() {
        it('should call listPaymentDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for listPaymentDetails call and complete the assertions
          /*

          instance.listPaymentDetails(customerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BillaBear.InlineResponse2005);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('makeDefaultPaymentDetails', function() {
        it('should call makeDefaultPaymentDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for makeDefaultPaymentDetails call and complete the assertions
          /*

          instance.makeDefaultPaymentDetails(customerId, paymentDetailsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('makeDefaultPaymentDetailsCustomer', function() {
        it('should call makeDefaultPaymentDetailsCustomer successfully', function(done) {
          // TODO: uncomment, update parameter values for makeDefaultPaymentDetailsCustomer call and complete the assertions
          /*

          instance.makeDefaultPaymentDetailsCustomer(customerId, paymentDetailsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('startFrontendPaymentDetails', function() {
        it('should call startFrontendPaymentDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for startFrontendPaymentDetails call and complete the assertions
          /*

          instance.startFrontendPaymentDetails(customerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BillaBear.FrontendToken);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
