/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.56
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/BillaBear/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/BillaBear/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillaBear);
  }
}(this, function(expect, BillaBear) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BillaBear.UsageApi();
  });

  describe('BillaBear', function() {
    describe('UsageApi', function() {
      describe('createCustomerUsageLimit', function() {
        it('should call createCustomerUsageLimit successfully', function(done) {
          // TODO: uncomment, update parameter values for createCustomerUsageLimit call and complete the assertions
          /*

          instance.createCustomerUsageLimit(body, customerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BillaBear.UsageLimit);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createEvent', function() {
        it('should call createEvent successfully', function(done) {
          // TODO: uncomment, update parameter values for createEvent call
          /*

          instance.createEvent(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('customerCustomerIdUasgeLimitLimitIdDelete', function() {
        it('should call customerCustomerIdUasgeLimitLimitIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for customerCustomerIdUasgeLimitLimitIdDelete call
          /*

          instance.customerCustomerIdUasgeLimitLimitIdDelete(customerId, usageLimitId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCustomerCosts', function() {
        it('should call getCustomerCosts successfully', function(done) {
          // TODO: uncomment, update parameter values for getCustomerCosts call and complete the assertions
          /*

          instance.getCustomerCosts(customerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BillaBear.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCustomerUsageLimitsById', function() {
        it('should call getCustomerUsageLimitsById successfully', function(done) {
          // TODO: uncomment, update parameter values for getCustomerUsageLimitsById call and complete the assertions
          /*

          instance.getCustomerUsageLimitsById(customerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BillaBear.InlineResponse2005);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
